// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL37BPjtsZatlKg_jbcUIHlf571fApIak',
    appId: '1:1069512086183:web:4543e249b74b65430c0182',
    messagingSenderId: '1069512086183',
    projectId: 'app-dev-4768b',
    authDomain: 'app-dev-4768b.firebaseapp.com',
    storageBucket: 'app-dev-4768b.firebasestorage.app',
    measurementId: 'G-YKYBPT2JXS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVGG9pQfGTOddAQlUH6LnRE4EEePfq1e0',
    appId: '1:1069512086183:android:fb8c6ba4fae84d540c0182',
    messagingSenderId: '1069512086183',
    projectId: 'app-dev-4768b',
    storageBucket: 'app-dev-4768b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh33xo6BO7TP2fhGnWsp_POg23U0V0ZtA',
    appId: '1:1069512086183:ios:b6b07d73d649c9090c0182',
    messagingSenderId: '1069512086183',
    projectId: 'app-dev-4768b',
    storageBucket: 'app-dev-4768b.firebasestorage.app',
    iosClientId: '1069512086183-4vpqu9tbnebc7eit7pm1mnbptash5otp.apps.googleusercontent.com',
    iosBundleId: 'com.example.gene',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDh33xo6BO7TP2fhGnWsp_POg23U0V0ZtA',
    appId: '1:1069512086183:ios:b6b07d73d649c9090c0182',
    messagingSenderId: '1069512086183',
    projectId: 'app-dev-4768b',
    storageBucket: 'app-dev-4768b.firebasestorage.app',
    iosClientId: '1069512086183-4vpqu9tbnebc7eit7pm1mnbptash5otp.apps.googleusercontent.com',
    iosBundleId: 'com.example.gene',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAL37BPjtsZatlKg_jbcUIHlf571fApIak',
    appId: '1:1069512086183:web:1422c9328e943cf50c0182',
    messagingSenderId: '1069512086183',
    projectId: 'app-dev-4768b',
    authDomain: 'app-dev-4768b.firebaseapp.com',
    storageBucket: 'app-dev-4768b.firebasestorage.app',
    measurementId: 'G-KTYD0PXVQS',
  );

}